# Generated by Django 4.1.1 on 2023-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='adImage',
            field=models.ImageField(blank=True, null=True, upload_to='img/services/ads'),
        ),
    ]
