# Generated by Django 4.1.1 on 2023-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_service_adimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Team Member', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('image', models.ImageField(default='img/members/male.png', upload_to='img/members')),
                ('phrase', models.CharField(default="Don't wait for an opportunity, create it", max_length=500)),
                ('twitter_handle', models.CharField(default='', max_length=1000)),
                ('fb', models.CharField(default='', max_length=1000)),
                ('linkedIn', models.CharField(default='', max_length=1000)),
                ('instangram', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'TeamMember',
                'verbose_name_plural': 'TeamMember',
            },
        ),
    ]
