# Generated by Django 4.1.1 on 2023-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='fb',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instangram',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedIn',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_handle',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
